In [14]:

import os
import pandas as pd


# 1. FILE PATHS


processed_dir = (
    r"C:\Users\Gabriela Shirkey\OneDrive - Chapman University"
    r"\CONNECT_SBG\Coastal-Tanner\SpectralEvolution"
    r"\LCDM_2005_3A02\LCDM_2005_3A02_processed"
)

metadata_file = os.path.join(
    processed_dir,
    "LCDM_050225_radiance_metadata.csv" #for the SED file names
)

output_file = os.path.join(
    processed_dir,
    "LCDM_050225_filenames_joined_sed_photoids.csv"
)

print(metadata_file)
print(output_file)

C:\Users\Gabriela Shirkey\OneDrive - Chapman University\CONNECT_SBG\Coastal-Tanner\SpectralEvolution\LCDM_2005_3A02\LCDM_2005_3A02_processed\LCDM_050225_radiance_metadata.csv
C:\Users\Gabriela Shirkey\OneDrive - Chapman University\CONNECT_SBG\Coastal-Tanner\SpectralEvolution\LCDM_2005_3A02\LCDM_2005_3A02_processed\LCDM_050225_filenames_joined_sed_photoids.csv

In [15]:
# 2. READ SPECTRAL METADATA

spectra_metadata = pd.read_csv(metadata_file) #this shows the SED metadata, which didn't take the GPS info

print(spectra_metadata.shape)
print(spectra_metadata.head())
print(spectra_metadata.tail())

(177, 4)
        filename  latitude  longitude  gps_time
0  1594452_00097       NaN        NaN       NaN
1  1594452_00098       NaN        NaN       NaN
2  1594452_00099       NaN        NaN       NaN
3  1594452_00100       NaN        NaN       NaN
4  1594452_00101       NaN        NaN       NaN
          filename  latitude  longitude  gps_time
172  1594452_00269       NaN        NaN       NaN
173  1594452_00270       NaN        NaN       NaN
174  1594452_00271       NaN        NaN       NaN
175  1594452_00272       NaN        NaN       NaN
176  1594452_00273       NaN        NaN       NaN

In [17]:
# 3. DEFINE QUADRAT METADATA
# These records come from the GIS quadrat attribute table.
#
# NOTE:
# Quadrat 54 is absent from the sampled dataset.
# Transect 7 begins at 10 m rather than 0 m.
# IMG_2467 / Quadrat 53 was corrected to 50 m.

quadrat_data = [
    # Transect 1
    ["IMG_2404.JPG", 33.589467, -117.868247, 0,  1, 1],
    ["IMG_2405.JPG", 33.589403, -117.868331, 10, 1, 2],
    ["IMG_2406.JPG", 33.589353, -117.868414, 20, 1, 3],
    ["IMG_2407.JPG", 33.589294, -117.868492, 30, 1, 4],
    ["IMG_2408.JPG", 33.589247, -117.868592, 40, 1, 5],
    ["IMG_2409.JPG", 33.589197, -117.868669, 50, 1, 6],

    # Transect 2
    ["IMG_2411.JPG", 33.589225, -117.868181, 0,  2, 7],
    ["IMG_2412.JPG", 33.589189, -117.868264, 10, 2, 8],
    ["IMG_2413.JPG", 33.589144, -117.868347, 20, 2, 9],
    ["IMG_2414.JPG", 33.589108, -117.868453, 30, 2, 10],
    ["IMG_2415.JPG", 33.589064, -117.868544, 40, 2, 11],
    ["IMG_2416.JPG", 33.589036, -117.868631, 50, 2, 12],

    # Transect 3
    ["IMG_2417.JPG", 33.589139, -117.868042, 0,  3, 13],
    ["IMG_2418.JPG", 33.589108, -117.868128, 10, 3, 14],
    ["IMG_2420.JPG", 33.589058, -117.868217, 20, 3, 15],
    ["IMG_2421.JPG", 33.589019, -117.868308, 30, 3, 16],
    ["IMG_2422.JPG", 33.588967, -117.868400, 40, 3, 17],
    ["IMG_2423.JPG", 33.588925, -117.868492, 50, 3, 18],

    # Transect 4
    ["IMG_2424.JPG", 33.589058, -117.867928, 0,  4, 19],
    ["IMG_2425.JPG", 33.589006, -117.868003, 10, 4, 20],
    ["IMG_2426.JPG", 33.588956, -117.868094, 20, 4, 21],
    ["IMG_2427.JPG", 33.588903, -117.868181, 30, 4, 22],
    ["IMG_2428.JPG", 33.588847, -117.868247, 40, 4, 23],
    ["IMG_2431.JPG", 33.588797, -117.868339, 50, 4, 24],

    # Transect 5
    ["IMG_2432.JPG", 33.588986, -117.867731, 0,  5, 25],
    ["IMG_2435.JPG", 33.588931, -117.867814, 10, 5, 26],
    ["IMG_2436.JPG", 33.588886, -117.867889, 20, 5, 27],
    ["IMG_2437.JPG", 33.588839, -117.867981, 30, 5, 28],
    ["IMG_2438.JPG", 33.588794, -117.868056, 40, 5, 29],
    ["IMG_2439.JPG", 33.588722, -117.868142, 50, 5, 30],

    # Transect 6
    ["IMG_2440.JPG", 33.588878, -117.867553, 0,  6, 31],
    ["IMG_2441.JPG", 33.588828, -117.867639, 10, 6, 32],
    ["IMG_2442.JPG", 33.588781, -117.867731, 20, 6, 33],
    ["IMG_2443.JPG", 33.588722, -117.867814, 30, 6, 34],
    ["IMG_2445.JPG", 33.588669, -117.867897, 40, 6, 35],
    ["IMG_2446.JPG", 33.588639, -117.867944, 50, 6, 36],

    # Transect 7
    ["IMG_2448.JPG", 33.588714, -117.867456, 0, 7, 37],
    ["IMG_2449.JPG", 33.588672, -117.867547, 10, 7, 38],
    ["IMG_2450.JPG", 33.588614, -117.867631, 20, 7, 39],
    ["IMG_2451.JPG", 33.588558, -117.867714, 30, 7, 40],
    ["IMG_2452.JPG", 33.588508, -117.867806, 40, 7, 41],
    ["IMG_2453.JPG", 33.588453, -117.867858, 50, 7, 42],

    # Transect 8
    ["IMG_2454.JPG", 33.588547, -117.867369, 0, 8, 43],
    ["IMG_2457.JPG", 33.588539, -117.867461, 10, 8, 44],
    ["IMG_2458.JPG", 33.588517, -117.867553, 20, 8, 45],
    ["IMG_2459.JPG", 33.588467, -117.867639, 30, 8, 46],
    ["IMG_2460.JPG", 33.588417, -117.867744, 40, 8, 47],
    ["IMG_2461.JPG", 33.588361, -117.867814, 50, 8, 48],

    # Transect 9
    ["IMG_2462.JPG", 33.588389, -117.867378, 0, 9, 49],
    ["IMG_2463.JPG", 33.588353, -117.867456, 10, 9, 50],
    ["IMG_2464.JPG", 33.588311, -117.867531, 20, 9, 51],
    ["IMG_2466.JPG", 33.588253, -117.867606, 30, 9, 52],
    ["IMG_2467.JPG", 33.588250, -117.867661, 40, 9, 53],
    ["IMG_2468.JPG", 33.588264, -117.867256, 50, 9, 55],

    # Transect 10
    # Quadrat 54 is absent.
    ["IMG_2469.JPG", 33.588228, -117.867311, 0, 10, 56],
    ["IMG_2471.JPG", 33.588164, -117.867403, 10, 10, 57],
    ["IMG_2472.JPG", 33.588111, -117.867486, 20, 10, 58],
    ["IMG_2473.JPG", 33.588056, -117.867553, 30, 10, 59],
    ["IMG_2474.JPG", 33.588028, -117.867586, 40, 10, 60],
]

quadrat_df = pd.DataFrame(
    quadrat_data,
    columns=[
        "photo_id",
        "latitude",
        "longitude",
        "distance_m",
        "transect",
        "quadrat_id"
    ]
)

print(quadrat_df.shape)
print(quadrat_df.head(10))
print(quadrat_df.tail(10))

(59, 6)
       photo_id   latitude   longitude  distance_m  transect  quadrat_id
0  IMG_2404.JPG  33.589467 -117.868247           0         1           1
1  IMG_2405.JPG  33.589403 -117.868331          10         1           2
2  IMG_2406.JPG  33.589353 -117.868414          20         1           3
3  IMG_2407.JPG  33.589294 -117.868492          30         1           4
4  IMG_2408.JPG  33.589247 -117.868592          40         1           5
5  IMG_2409.JPG  33.589197 -117.868669          50         1           6
6  IMG_2411.JPG  33.589225 -117.868181           0         2           7
7  IMG_2412.JPG  33.589189 -117.868264          10         2           8
8  IMG_2413.JPG  33.589144 -117.868347          20         2           9
9  IMG_2414.JPG  33.589108 -117.868453          30         2          10
        photo_id   latitude   longitude  distance_m  transect  quadrat_id
49  IMG_2463.JPG  33.588353 -117.867456          10         9          50
50  IMG_2464.JPG  33.588311 -117.867531          20         9          51
51  IMG_2466.JPG  33.588253 -117.867606          30         9          52
52  IMG_2467.JPG  33.588250 -117.867661          40         9          53
53  IMG_2468.JPG  33.588264 -117.867256          50         9          55
54  IMG_2469.JPG  33.588228 -117.867311           0        10          56
55  IMG_2471.JPG  33.588164 -117.867403          10        10          57
56  IMG_2472.JPG  33.588111 -117.867486          20        10          58
57  IMG_2473.JPG  33.588056 -117.867553          30        10          59
58  IMG_2474.JPG  33.588028 -117.867586          40        10          60

In [18]:
#repeat the image's GPS and quadrat/transect info 3 times and merge with SED data.
#this is because we took 3 spectral SED samples per quadrat

quadrat_repeated = quadrat_df.loc[
    quadrat_df.index.repeat(3)
].reset_index(drop=True)

quadrat_repeated["replicate"] = (
    quadrat_repeated.groupby("quadrat_id").cumcount() + 1
)

print(quadrat_repeated.shape)
print(quadrat_repeated.head(12))

(177, 7)
        photo_id   latitude   longitude  distance_m  transect  quadrat_id  \
0   IMG_2404.JPG  33.589467 -117.868247           0         1           1
1   IMG_2404.JPG  33.589467 -117.868247           0         1           1
2   IMG_2404.JPG  33.589467 -117.868247           0         1           1
3   IMG_2405.JPG  33.589403 -117.868331          10         1           2
4   IMG_2405.JPG  33.589403 -117.868331          10         1           2
5   IMG_2405.JPG  33.589403 -117.868331          10         1           2
6   IMG_2406.JPG  33.589353 -117.868414          20         1           3
7   IMG_2406.JPG  33.589353 -117.868414          20         1           3
8   IMG_2406.JPG  33.589353 -117.868414          20         1           3
9   IMG_2407.JPG  33.589294 -117.868492          30         1           4
10  IMG_2407.JPG  33.589294 -117.868492          30         1           4
11  IMG_2407.JPG  33.589294 -117.868492          30         1           4

    replicate
0           1
1           2
2           3
3           1
4           2
5           3
6           1
7           2
8           3
9           1
10          2
11          3

In [19]:
# 4. ASSIGN EACH SED MEASUREMENT TO A QUADRAT

# Reset the index so both tables run from row 0 to row 176
spectra_metadata = spectra_metadata.reset_index(drop=True)

# Combine the SED filename with the repeated quadrat information
spectral_quadrat_metadata = pd.concat(
    [
        spectra_metadata[["filename"]],
        quadrat_repeated
    ],
    axis=1 #put the tables beside each other as new columns, rather than stacking one underneath the other.
)

print(spectral_quadrat_metadata.shape)

spectral_quadrat_metadata.head(12)

(177, 8)

,filename,photo_id,latitude,longitude,distance_m,transect,quadrat_id,replicate
0,1594452_00097,IMG_2404.JPG,33.589467,-117.868247,0,1,1,1
1,1594452_00098,IMG_2404.JPG,33.589467,-117.868247,0,1,1,2
2,1594452_00099,IMG_2404.JPG,33.589467,-117.868247,0,1,1,3
3,1594452_00100,IMG_2405.JPG,33.589403,-117.868331,10,1,2,1
4,1594452_00101,IMG_2405.JPG,33.589403,-117.868331,10,1,2,2
5,1594452_00102,IMG_2405.JPG,33.589403,-117.868331,10,1,2,3
6,1594452_00103,IMG_2406.JPG,33.589353,-117.868414,20,1,3,1
7,1594452_00104,IMG_2406.JPG,33.589353,-117.868414,20,1,3,2
8,1594452_00105,IMG_2406.JPG,33.589353,-117.868414,20,1,3,3
9,1594452_00106,IMG_2407.JPG,33.589294,-117.868492,30,1,4,1
10,1594452_00107,IMG_2407.JPG,33.589294,-117.868492,30,1,4,2
11,1594452_00108,IMG_2407.JPG,33.589294,-117.868492,30,1,4,3

In [20]:
# 5. CHECK TRANSECT TRANSITIONS

# Show the end of Transect 7 and beginning of Transect 8
spectral_quadrat_metadata[
    spectral_quadrat_metadata["quadrat_id"].between(40, 43)
]

,filename,photo_id,latitude,longitude,distance_m,transect,quadrat_id,replicate
117,1594452_00214,IMG_2451.JPG,33.588558,-117.867714,30,7,40,1
118,1594452_00215,IMG_2451.JPG,33.588558,-117.867714,30,7,40,2
119,1594452_00216,IMG_2451.JPG,33.588558,-117.867714,30,7,40,3
120,1594452_00217,IMG_2452.JPG,33.588508,-117.867806,40,7,41,1
121,1594452_00218,IMG_2452.JPG,33.588508,-117.867806,40,7,41,2
122,1594452_00219,IMG_2452.JPG,33.588508,-117.867806,40,7,41,3
123,1594452_00220,IMG_2453.JPG,33.588453,-117.867858,50,7,42,1
124,1594452_00221,IMG_2453.JPG,33.588453,-117.867858,50,7,42,2
125,1594452_00222,IMG_2453.JPG,33.588453,-117.867858,50,7,42,3
126,1594452_00223,IMG_2454.JPG,33.588547,-117.867369,0,8,43,1
127,1594452_00224,IMG_2454.JPG,33.588547,-117.867369,0,8,43,2
128,1594452_00225,IMG_2454.JPG,33.588547,-117.867369,0,8,43,3

In [21]:
# Check the end of Transect 9 and beginning of Transect 10
# we should not see a quadrat 54 in here, which was not sampled. 
spectral_quadrat_metadata[
    spectral_quadrat_metadata["quadrat_id"].between(52, 56)
]

,filename,photo_id,latitude,longitude,distance_m,transect,quadrat_id,replicate
153,1594452_00250,IMG_2466.JPG,33.588253,-117.867606,30,9,52,1
154,1594452_00251,IMG_2466.JPG,33.588253,-117.867606,30,9,52,2
155,1594452_00252,IMG_2466.JPG,33.588253,-117.867606,30,9,52,3
156,1594452_00253,IMG_2467.JPG,33.588250,-117.867661,40,9,53,1
157,1594452_00254,IMG_2467.JPG,33.588250,-117.867661,40,9,53,2
158,1594452_00255,IMG_2467.JPG,33.588250,-117.867661,40,9,53,3
159,1594452_00256,IMG_2468.JPG,33.588264,-117.867256,50,9,55,1
160,1594452_00257,IMG_2468.JPG,33.588264,-117.867256,50,9,55,2
161,1594452_00258,IMG_2468.JPG,33.588264,-117.867256,50,9,55,3
162,1594452_00259,IMG_2469.JPG,33.588228,-117.867311,0,10,56,1
163,1594452_00260,IMG_2469.JPG,33.588228,-117.867311,0,10,56,2
164,1594452_00261,IMG_2469.JPG,33.588228,-117.867311,0,10,56,3

In [10]:
# 6. VALIDATE SPECTRAL-QUADRAT ASSIGNMENTS

# Check total numbers
assert len(quadrat_df) == 59, "Expected 59 sampled quadrats."
assert len(spectra_metadata) == 177, "Expected 177 SED measurements."
assert len(spectral_quadrat_metadata) == 177, "Expected 177 assigned spectra."

# Check that every sampled quadrat has exactly 3 spectra
spectra_per_quadrat = (
    spectral_quadrat_metadata
    .groupby("quadrat_id")
    .size()
)

assert (spectra_per_quadrat == 3).all(), \
    "At least one quadrat does not have exactly 3 spectra."

# Check first and last SED measurements
assert spectral_quadrat_metadata.iloc[0]["filename"] == "1594452_00097"
assert spectral_quadrat_metadata.iloc[-1]["filename"] == "1594452_00273"

# Check that Quadrat 54 is correctly absent
assert 54 not in spectral_quadrat_metadata["quadrat_id"].values

print("All validation checks passed.")
print(f"Quadrats: {spectral_quadrat_metadata['quadrat_id'].nunique()}")
print(f"Spectra: {len(spectral_quadrat_metadata)}")
print(f"Transects: {spectral_quadrat_metadata['transect'].nunique()}")

All validation checks passed.
Quadrats: 59
Spectra: 177
Transects: 10

In [22]:
# 7. SAVE SPECTRAL-QUADRAT METADATA

spectral_quadrat_metadata.to_csv(
    output_file,
    index=False
)

print(f"Saved quadrat assignments to:\n{output_file}")

Saved quadrat assignments to:
C:\Users\Gabriela Shirkey\OneDrive - Chapman University\CONNECT_SBG\Coastal-Tanner\SpectralEvolution\LCDM_2005_3A02\LCDM_2005_3A02_processed\LCDM_050225_filenames_joined_sed_photoids.csv